# Cartesian planner configuration parameters
  /planner_cartesian/run_period: 0.01           # Node execution period
  /planner_cartesian/start_delay: 0.5           # Execution start delay

  /planner_cartesian/pi: [0.3, 0.0, 0.2]            # Initial position [m]
  /planner_cartesian/pf: [0.0, 0.4, 0.0]            # Final position [m]

  /planner_cartesian/max_acc: 0.5               # Maximum acceleration [m/s^2]
  /planner_cartesian/max_vel: 1.0               # Maximum velocity [m/s]

  /planner_cartesian/elbow_high: false          # Inverse kinematic solution (elbow high/elbow low)
  
  /planner_cartesian/link_length: [0.337, 0.210, 0.268, 0, 0.174, 0]    # Link length [m]
